Interactive Shell Autocomplete Feature
grapheneX/grapheneX pull request #25
Opened 2019-04-25 16:46 UTC by bufgix

## Description
Added Interactive shell autocomplete feature. This feature provides  autocomplete to custom namespaces or modules 

`help` + `TAB` -> show available commands (already working)
`switch` + `TAB` -> show namespaces
`use`+ `TAB` -> show modules

## How Has This Been Tested?
I  tested on Windows 10.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/22038798/56753006-4874a180-6792-11e9-83e8-8404405d74d6.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-04-25 19:36 UTC, KeyLo99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Interactive Shell Autocomplete Feature](https://trello.com/c/OLMyUJN3/32-interactive-shell-autocomplete-feature)

2019-04-25 19:48 UTC, orhun requested changes
We don't need to import `get_modules` function and call it inside every function that is responsible for auto complete feature since we can access the static modules dictionary with `self.module`. (Which was declared at [here](https://github.com/grapheneX/grapheneX/blob/dev/core/cli/shell.py#L11))
So we should replace the `get_modules` calls with `self.modules` I think.

2019-04-25 20:31 UTC, bufgix commented
> We don't need to import `get_modules` function and call it inside every function that is responsible for auto complete feature since we can access the static modules dictionary with `self.module`. (Which was declared at [here](https://github.com/grapheneX/grapheneX/blob/dev/core/cli/shell.py#L11))
> So we should replace the `get_modules` calls with `self.modules` I think.

Fixed https://github.com/grapheneX/grapheneX/pull/25/commits/69625ec960f1a537e25262f8afed7dca99d02d2d

2019-04-25 20:38 UTC, orhun approved these changes

2019-04-26 18:38 UTC, furk4nyuksel approved these changes
![tested](https://user-images.githubusercontent.com/26774223/56829082-7aa60200-686b-11e9-8004-e160caa09033.JPG)
 I didn't come across any problems

2019-04-27 12:49 UTC, EnesOkutan commented
"use ke" and tab press, not complete. doesn't it have to complete the "kernel" ?
And this completion occurs in a case insensitive way. Is this a problem?

2019-04-27 20:49 UTC, kalaycitayfun approved these changes

2019-04-27 22:08 UTC, KeyLo99 commented on core/cli/commands.py
> +                    AVAILABLE_MODULES.append(f"{key.upper()}.{name}")
It is not finding the right module with this.
Should be: `AVAILABLE_MODULES.append(f"{key}/{name}")`

2019-04-27 22:37 UTC, KeyLo99 commented on core/cli/commands.py
> +                    AVAILABLE_MODULES.append(f"{key.upper()}.{name}")
And also I changed the function a little bit for the comfort of my fingers.
Maybe you will consider:
```
def complete_use(self, text, line, begidx, endidx):
        AVAILABLE_MODULES = self.modules.get(self.namespace)
        if AVAILABLE_MODULES is None:  # if self.namespace == ''
            AVAILABLE_MODULES = list()
            for key, value in self.modules.items():
                for name, module in value.items():
                    AVAILABLE_MODULES.append(f"{key}/{name}")
        mline = line.partition(' ')[2]
        offs = len(mline) - len(text)
        #######
        # Get completed text with namespace
        comp_text =  [s[offs:] for s in AVAILABLE_MODULES if s.startswith(mline)]
        # If no namespace found
        if len(comp_text) == 0:
            # Try to complete with module names
            AVAILABLE_MODULES = self.modules.get(list(self.modules.keys())[0])
            comp_text = [s[offs:] for s in AVAILABLE_MODULES if s.startswith(mline)]
        # Return
        return comp_text
        #######
```

2019-04-27 22:39 UTC, KeyLo99 commented on core/cli/commands.py
> +                    AVAILABLE_MODULES.append(f"{key.upper()}.{name}")
Another _nacizane_ idea of mine: Maybe we can move the part that responsible for creating the `AVAILABLE_MODULES` dict. It's just creating that dictionary over and over again on TAB key presses.

2019-04-27 23:05 UTC, KeyLo99 commented on core/cli/commands.py
> +                    AVAILABLE_MODULES.append(f"{key.upper()}.{name}")
+ I've updated the code above.
(Tried to solve case sensitivity issue.)

2019-04-28 08:10 UTC, EnesOkutan requested changes
"use Log" + tab does not work.
In the last commit, the entries are converted to lowercase, but the module names in the variable AVAILABLE_MODULES are in the original name.

2019-04-28 09:46 UTC, afk approved these changes

2019-04-28 09:49 UTC, KeyLo99 commented
> "use Log" + tab does not work.
> In the last commit, the entries are converted to lowercase, but the module names in the variable AVAILABLE_MODULES are in the original name.

Can you test my code above? I've solved that issue.

2019-04-28 10:05 UTC, EnesOkutan commented
What code are you talking about?

2019-04-28 10:36 UTC, KeyLo99 commented
> What code are you talking about?

https://github.com/grapheneX/grapheneX/pull/25#discussion_r279170497

2019-04-28 11:41 UTC, EnesOkutan commented
I'm not sure, I don't think it meets exactly.
for example:

use kernel/Logs_R + <tab> , does not work. 

Since you are applying the capitalize function, the following situation occurs: "kernel/Logs_r"
So the searched module cannot be found in the array.

2019-04-28 11:59 UTC, KeyLo99 commented
> I'm not sure, I don't think it meets exactly.
> for example:
> 
> use kernel/Logs_R + tab , does not work.
> 
> Since you are applying the capitalize function, the following situation occurs: "kernel/Logs_r"
> So the searched module cannot be found in the array.

Aight, how about this?

`mline = mline.split('/')[0] + "/" + mline.split('/')[1].title()`

2019-04-28 12:01 UTC, EnesOkutan commented
Looks fine !

2019-04-28 12:04 UTC, KeyLo99 commented
```
def complete_use(self, text, line, begidx, endidx):
        avb_modules = self.modules.get(self.namespace)
        if avb_modules is None:
            avb_modules = list()
            for key, value in self.modules.items():
                for name, module in value.items():
                    avb_modules.append(f"{key}/{name}")
        mline = line.partition(' ')[2]
        #######
        # If namespace selected
        if '/' in mline:
            # title() given module string for getting rid of case sensitivity
            mline = mline.replace(mline.split('/')[1], mline.split('/')[1].title())
        offs = len(mline) - len(text)
        # Get completed text with namespace
        comp_text =  [s[offs:] for s in avb_modules if s.startswith(mline)]
        # If no namespace found
        if len(comp_text) == 0:
            # Try to complete with module names
            avb_modules = self.modules.get(list(self.modules.keys())[0])
            mline = mline.title()
            comp_text = [s[offs:] for s in avb_modules if s.startswith(mline)]
        # Return
        #print(comp_text)
        return comp_text
        #######
```

2019-04-28 12:04 UTC, KeyLo99 commented
```
    def complete_switch(self, text, line, begidx, endidx):
        avb_namespaces = [i.lower() for i in self.modules.keys()]
        mline = line.lower().partition(' ')[2]
        offs = len(mline) - len(text)
        return [s[offs:] for s in avb_namespaces if s.startswith(mline)]
```

2019-04-28 12:05 UTC, KeyLo99 commented
@bufgix Please consider https://github.com/grapheneX/grapheneX/pull/25#issuecomment-487372893 and https://github.com/grapheneX/grapheneX/pull/25#issuecomment-487372966

2019-04-28 12:07 UTC, EnesOkutan commented
mline = mline.split('/')[0].lower() + "/" + mline.split('/')[1].title()
In this way, the namespace is case insensitive.

2019-04-28 12:12 UTC, KeyLo99 commented
> mline = mline.split('/')[0].lower() + "/" + mline.split('/')[1].title()
> In this way, the namespace is case insensitive.

:+1: Edited the code above

2019-04-28 13:16 UTC, orhun approved these changes

2019-04-28 13:17 UTC, KeyLo99 commented
@EnesOkutan waiting for your approval for merging.

2019-04-28 14:11 UTC, EnesOkutan commented
`avb_modules = self.modules.get(list(self.modules.keys())[0])`

I'm not sure this is correct

2019-04-28 14:15 UTC, EnesOkutan commented
Doesn't cause error when there is more than one namespace?

2019-04-28 14:17 UTC, KeyLo99 commented
> `avb_modules = self.modules.get(list(self.modules.keys())[0])`
> 
> I'm not sure this is correct

Why? I don't understand.

2019-04-28 14:18 UTC, KeyLo99 commented
> Doesn't cause error when there is more than one namespace?

What do you mean "more than one namespace"?

2019-04-28 14:21 UTC, KeyLo99 commented
I'd be appreciated if you send us the "correct" code. (Personally I don't want to handle more issues on this PR)

2019-04-28 14:25 UTC, EnesOkutan commented
This code always gets the first namespace kernel in self.modules. For example, if we think that there is a namespace called "networking", I always think that getting a first module would be an error.

2019-04-28 14:32 UTC, KeyLo99 commented
> This code always gets the first namespace kernel in self.modules. For example, if we think that there is a namespace called "networking", I always think that getting a first module would be an error.
> 
> Or is there a misunderstanding, other namespace from kernel namespace

Yup, that looks like so. I didn't test the code but it sounds like an error. 
We should get  the `avb_modules` list via `self.namespace` variable.
@bufgix or @EnesOkutan please fix it soon. (Not that hard though)

2019-04-28 15:29 UTC, KeyLo99 commented
> > This code always gets the first namespace kernel in self.modules. For example, if we think that there is a namespace called "networking", I always think that getting a first module would be an error.
> > Or is there a misunderstanding, other namespace from kernel namespace
> 
> Yup, that looks like so. I didn't test the code but it sounds like an error.
> We should get the `avb_modules` list via `self.namespace` variable.
> @bufgix or @EnesOkutan please fix it soon. (Not that hard though)

nvm -_-

2019-04-28 15:31 UTC, EnesOkutan commented
![image](https://user-images.githubusercontent.com/36725317/56866596-8f4cdc00-69ca-11e9-8944-4ccb94d06f39.png)

I have such a solution but I'm not sure it's the optimal code.

2019-04-28 15:38 UTC, EnesOkutan approved these changes
congratulations, fixed problem.

2019-04-28 15:49 UTC, merged