Harden Command Added
grapheneX/grapheneX pull request #26
Opened 2019-04-25 18:48 UTC by afk

## Description
`harden` command added.
Redirection operator wasn't working, so a handler was written for these operators.

## How Has This Been Tested?
Ran the command on Ubuntu 18.04.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-04-25 19:36 UTC, KeyLo99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Interactive Shell <harden()>](https://trello.com/c/Tn6RXgEW/24-interactive-shell-harden)

2019-04-25 19:42 UTC, KeyLo99 commented on core/cli/commands.py
> +        logger.info(run_cmd(cmd))
Is it okay for printing executed command's output as `info`? Maybe we can use just `print` since we don't check the output.

2019-04-25 20:42 UTC, bufgix approved these changes

2019-04-26 08:37 UTC, orhun approved these changes

2019-04-26 18:26 UTC, furk4nyuksel reviewed
![hat](https://user-images.githubusercontent.com/26774223/56828369-d1124100-6869-11e9-90a6-66a57d8fe0d6.JPG)
The harden command did not work

2019-04-26 19:22 UTC, KeyLo99 commented
> ![hat](https://user-images.githubusercontent.com/26774223/56828369-d1124100-6869-11e9-90a6-66a57d8fe0d6.JPG)
> The harden command did not work

It's because you use it in a wrong way.
Correct usage is:
`use disable_rdp`
`harden`

2019-04-26 20:02 UTC, ibanez75612 commented
> > ![hat](https://user-images.githubusercontent.com/26774223/56828369-d1124100-6869-11e9-90a6-66a57d8fe0d6.JPG)
> > The harden command did not work
> 
> It's because you use it in a wrong way.
> Correct usage is:
> `use disable_rdp`
> `harden`

![aa](https://user-images.githubusercontent.com/26774223/56833504-53edc880-6877-11e9-9818-355e60464001.JPG)

Is working now

2019-04-26 20:02 UTC, furk4nyuksel approved these changes

2019-04-26 20:05 UTC, orhun requested changes
I had chance to test this code out and I found a bug.
Code: `self.modules[self.namespace][self.module]()`
What I'm doing is `use logs_restrict_access`
So we can't run harden command unless we select a namespace.
Also it is case sensitive so throws KeyError when you don't care about the capital letters.
Please fix.

2019-04-27 09:46 UTC, EnesOkutan commented
Can we solve this problem in a different way?
my suggestion:
By creating a dictionary with name definitions, we can solve it without the need for a loop.
For Example:
dict = { 'disable_rdp' : 'Disable_RDP' }
Assuming we create such a dict, we can re-create the code as follows:

![image](https://user-images.githubusercontent.com/36725317/56847884-42390f00-68d1-11e9-9547-242be649cfe4.png)

2019-04-27 12:23 UTC, EnesOkutan commented
If notative speeds (complexity) are of importance, we can get rid of the loops of these codes in this way.

![image](https://user-images.githubusercontent.com/36725317/56849696-3ce6bf00-68e7-11e9-81bf-ae597ddc44f5.png)

2019-04-27 18:04 UTC, KeyLo99 commented
> Can we solve this problem in a different way?
> my suggestion:
> By creating a dictionary with name definitions, we can solve it without the need for a loop.
> For Example:
> dicti = { 'disable_rdp' : 'Disable_RDP' }
> Assuming we create such a dict, we can re-create the code as follows:
> 
> ![image](https://user-images.githubusercontent.com/36725317/56847884-42390f00-68d1-11e9-9547-242be649cfe4.png)

Which 'problem' are you talking about exactly?

2019-04-27 18:08 UTC, EnesOkutan commented
No problem, just an idea of ​​how the code will be healthier.

2019-04-27 18:09 UTC, KeyLo99 commented
> No problem, just an idea of ​​how the code will be healthier.

Oh, got it.

2019-04-27 18:12 UTC, orhun approved these changes

2019-04-27 20:16 UTC, EnesOkutan approved these changes
Congratulations, it works.

2019-04-27 20:37 UTC, merged